language: node_js
node_js:
  - "6"
before_script:
  - "npm install"
  - "sudo apt-get update"
  - "sudo apt-get install graphicsmagick"
  - chmod 755 ./travis/push.sh
script:
  - "gulp build"
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_TOKEN
  repo: roobottom/roobottom-2017-live
  on:
    branch: master
